name: Generate Minesweeper

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta cada medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Minesweeper
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Generate Minesweeper SVG
        uses: Jair0305/github-contribution-minesweeper@main
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}